name: ⁉️ Help request
description: Need help with something? Ask here!
labels: ["question", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out for help! Please fill out the following sections to help us understand your issue.
  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: "I have read and agree to the [code of conduct](https://github.com/extphprs/ext-php-rs/blob/master/CODE_OF_CONDUCT.md)"
          required: true
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a clear and concise description of the problem you are facing."
      placeholder: |
        ## Description
        A clear and concise description of the issue.

        ## Example

        **Extension Code:**
        ```rs
        ```

        **PHP Code:**
        ```php
        <?php
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: PHP Version
      description: |
        Please run `php -v` and provide the full output of that command.
      placeholder: |
        PHP 8.4.8 (cli) (built: Jun  3 2025 16:29:26) (NTS)
        Copyright (c) The PHP Group
        Zend Engine v4.4.8, Copyright (c) Zend Technologies
      render: plain
  - type: input
    attributes:
      label: "`ext-php-rs` Version"
      description: "Please provide the exact version of the extension you are using."
      placeholder: "0.1.2 or git commit hash"
  - type: input
    attributes:
      label: Repository
      description: "If this issue is related to one of your repositories, please provide the repository link. (No advertising!)"
      placeholder: "https://github.com/user/your-repo"
  - type: checkboxes
    attributes:
      label: I have already tried
      description: "Please make sure you have tried the following before asking for help."
      options:
        - label: "Searching the documentation and guide"
          required: true
        - label: "Searching existing issues"
          required: true
