name: Benchmarks

on:
  push:
    branches: master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  clang: "17"
  php_version: "8.4"

jobs:
  benchmarks:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
        env:
          debug: true
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            benches
            benches/ext
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v6
        with:
          path: ${{ runner.temp }}/llvm-${{ env.clang }}
          key: ubuntu-latest-llvm-${{ env.clang }}
      - name: Setup LLVM & Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: ${{ env.clang }}
          directory: ${{ runner.temp }}/llvm-${{ env.clang }}
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Configure Clang
        run: |
          echo "LIBCLANG_PATH=${{ runner.temp }}/llvm-${{ env.clang }}/lib" >> $GITHUB_ENV
      - uses: taiki-e/install-action@cargo-binstall
      - name: Install cargo-codspeed
        run: cargo binstall --no-confirm cargo-codspeed
      - name: Build extension and benchmarks
        working-directory: benches
        run: |
          cargo build --manifest-path ext/Cargo.toml --release
          cargo codspeed build
      - name: Run Benchmarks
        uses: CodSpeedHQ/action@v5
        with:
          mode: simulation
          simulation-track-subprocess: true
          working-directory: benches
          run: cargo codspeed run
